---
$schemaver: '2.0'
repo_url: https://github.com/byu-oit/shared-admissions-college-summary
software:
  - name: shared-admissions-college-summary
    type: Command-line App
    aliases:
    short_description: Self-reported college information for shared admissions using
        scatter-gather pattern in AWS.
    assignment_group: gro:AD-Academic Information Management
    notes:
    maintained_by:
      - arasmus8
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit/shared-admissions-college-summary
        swagger_urls:
    microservice: false
    technologies_used:
      - JavaScript
      - Shell
    stages:
        production:
            urls:
                product_page: https://github.com/byu-oit/shared-admissions-college-summary
                physical_url:
                virtual_url:
            hosting_location:
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: confidential
        app: shared-admissions-college-summary
        team: gro:AD-Academic Information Management
